# full guide of options:
# https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html

# also perhaps we don't need the recipe at all?
# https://conda.io/docs/user-guide/tasks/build-packages/build-without-recipe.html

# To see what comes out after this template is processed, run:
#    conda-render ./conda/

{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.name }}
  version: "{{ data.version }}"

source:
  # Source from a local path
  path: ..

  # Source from tarball
  # url: https://pypi.python.org/packages/source/fastai/fastai/fastai-1.0.0b.tar.gz
  # sha1: f0a2c9a30073449cfb7d171c57552f3109d93894

  # Source from git
  # git_rev: v0.13.1
  # git_url: https://github.com/fastai/fastai_pytorch.git

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

# unlike pypi, conda has a slightly different format for required
# versions, we must use - torch >=0.4.9 (note, there is only one
# space), for details see:
# https://conda.io/docs/user-guide/tasks/build-packages/package-spec.html#package-match-specifications
requirements:
  build:
    - conda-build
    - pytest-runner
    - python
    - torchvision 0.2.1 py_0

# skipped requirements:
# jupyter_contrib_nbextensions - only needed for internal tools - it's not on conda and requires too many of its own dependencies which aren't on conda either
# XXX: change pytorch-nightly to pytorch >=1.0.0 once it's released
# XXX: how to check not to require dataclasses for python 3.7+
#
# note: "module # [py36]" tells conda-build that this requirement is only for python3.6, it's not a comment.
  run:
    - dataclasses # [py36]
    - fastprogress
    - ipython
    - matplotlib
    - nbconvert
    - nbformat
    - numpy >=1.12
    - pandas
    - pillow
    - python
    - requests
    - scipy
    - spacy
    - traitlets
    - typing
    - pytorch-nightly
    - torchvision 0.2.1 py_0

# removing until pytorch-1.0.0 release - conda can't handle these dependencies and tries to pull in pytorch-0.4.1 due to torchvision depending on it. yet, pytorch doesn't release torchvision nightly build... no way out
#    - pytorch >=1.0.0

test:
  imports:
    - fastai

  requires:
    - python
    - pytest
    - numpy >=1.12

about:
  home: {{ data.get('url') }}
  license: {{ data['license'] }}
  license_family: APACHE
  license_file: LICENSE
  summary: {{ data['description'] }}
  description: "{{ data['long_description']|replace('"', "'") }}"
  doc_url: {{ data.get('url') }}
  dev_url: {{ data.get('url') }}

extra:
  deploy:
    - anaconda-client
    - setuptools >=0.39
    - twine >=1.12
  recipe-maintainers: ''
